language: node_js
cache:
  diretories:
    - node_modules
notifications:
  email: false
node_js:
  - 7
  - 6
before_script:
  - npm prune
  - typings install
  - npm install jasmine --global
script:
  - npm run build
  - npm run buildprod
  - npm run test